name: SwiftShader

env:
  SWIFTSHADER_LD_LIBRARY_PATH: swiftshader/build
  SWIFTSHADER_SHA: master

# on: workflow_dispatch

on: push

jobs:
  swiftshader:
    name: Clone and Build SwiftShader
    runs-on: ubuntu-latest
    steps:
    # - name: Check cache
    #   uses: actions/cache@v2
    #   env:
    #     cache-name: cache-swiftshader
    #   with:
    #     path: swiftshader
    #     key: ${{ runner.os }}-build-16636f4
    #     restore-keys: |
    #       ${{ runner.os }}-build-

    - name: Clone SwiftShader
      run: |
        git clone https://github.com/google/swiftshader --branch master --single-branch swiftshader

    - name: Build SwiftShader
      working-directory: swiftshader
      run: |
        git config advice.detachedHead false
        git checkout ${SWIFTSHADER_SHA}
        cd build
        cmake .. && make -j

  filament:
    name: Build Filament with SwiftShader support
    runs-on: ubuntu-latest
    needs: swiftshader
    steps:
    - uses: actions/checkout@v1
    - name: Verify SwiftShader library
      run: |
        ls swiftshader/build
    - name: Build Filament with SwiftShader support
      run: |
        ./build.sh -t release gltf_viewer
